name: philip
channels:
 - conda
 - defaults

dependencies:
 - python=3.7
 - matplotlib
 - numpy
 - pandas
 - sklearn
 - transformers
 - torch

#Required packages already included in Python standard library:
#collections
#csv
#json
#operator
#os
#sys
#random